furniture_shop/about_us/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from .views import AboutUs, Contact, Services
from furniture_shop.settings import MEDIA_URL, MEDIA_ROOT



app_name = 'about'


urlpatterns = [
    path('', AboutUs.as_view(), name='about'),
    path('contact/', Contact.as_view(), name='contact'),
    path('services/', Services.as_view(), name='services'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

furniture_shop/furniture_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from furniture_shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('about/', include('about_us.urls', namespace='about')),
    path('user/', include('user.urls', namespace='user')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

furniture_shop/products/urls.py
from django.urls import path, include
from .views import IndexView, ProductsView, ProductDetailView
from furniture_shop.settings import MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static


app_name = 'products'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('products/', ProductsView.as_view(), name='product_list'),
    path('products/<str:product_id>/', ProductDetailView.as_view(), name='product_detail'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

furniture_shop/user/urls.py
from django.urls import path
from .views import LoginView, RegisterView, UserProfileView, logout_view, UserProfileEdit
from django.conf.urls.static import static
from furniture_shop.settings import MEDIA_ROOT, MEDIA_URL

app_name = 'user'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('logout/', logout_view, name='logout'),
    path('profile/edit/', UserProfileEdit.as_view(), name='profile_edit'),
] + static(MEDIA_URL,document_root=MEDIA_ROOT)

furniture_shop/products/models.py
from django.db import models
from user.models import Customer
from django_quill.fields import QuillField


class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'category'
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.IntegerField()
    special_property = models.TextField()
    firs_page = models.BooleanField(default=False)

    class Meta:
        db_table = 'product'
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name


class Basket(models.Model):
    user = models.ForeignKey(to=Customer, on_delete=models.CASCADE)
    items = models.ManyToManyField(to=Product)

    class Meta:
        db_table = 'basket'
        verbose_name = 'basket'
        verbose_name_plural = 'basket'


class Comment(models.Model):
    rate = [
        ("1","1"),
        ("2","2"),
        ("3","3"),
        ("4","4"),
        ("5","5"),
    ]
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE, null=True, blank=True)
    author  = models.ForeignKey(to=Customer, on_delete=models.CASCADE, null=True, blank=True)
    content = models.TextField()
    rating = models.CharField(choices=rate, default=0, max_length=5)

    class Meta:
        db_table = 'comment'
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

    def __str__(self):
        return self.content


class BoughtItem(models.Model):
    products = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    user = models.ForeignKey(to=Customer, on_delete=models.CASCADE)

    class Meta:
        db_table = 'bought_item'
        verbose_name = 'bought_item'
        verbose_name_plural = 'bought_items'

    def __str__(self):
        return self.user.user_profile.username + " bought items"


class Image(models.Model):
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    # each product has images and each image has one product
    image = models.ImageField(upload_to='product_pictures/')

    class Meta:
        db_table = 'image'
        verbose_name = 'image'
        verbose_name_plural = 'images'

    def __str__(self):
        return self.image.url

furniture_shop/products/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import View
from .models import Product, Image, Comment, Category
from random import shuffle


app_name = 'products'


class IndexView(View):
    http_method_names = ['get', 'post']

    def get(self, request: any) -> HttpResponse:
        products = Product.objects.all()[:6]
        indexed_products = Product.objects.filter(firs_page=True)
        product_details = []
        indexed_product_details = []
        # === === === === === === === === === === === === === === === === === ===
        # 6 products in the index page
        for product in products:
            images = Image.objects.filter(product__name=product.name)
            product_details.append({
                'name': product.name,
                'price': product.price,
                'image': images[0],
                'product_id': str(product.id),
            })
        shuffle(product_details)
        # === === === === === === === === === === === === === === === === === ===
        # 4 products which are indexed in the index page
        for product in indexed_products:
            image = Image.objects.filter(product__name=product.name)
            indexed_product_details.append({
                'name': product.name,
                'price': product.price,
                'image': image[0],
                'description': product.description,
                'product_id': str(product.id),
            })
        # === === === === === === === === === === === === === === === === === ===
        context = {
            'product_details': product_details,
            'indexed_products': indexed_product_details,
        }
        return render(request, 'index.html', context)


class ProductsView(View):
    http_method_names = ['get', 'post']

    def get(self, request: any) -> HttpResponse:
        products = Product.objects.all()
        product_details = []
        for product in products:
            images = Image.objects.filter(product__name=product.name)
            product_details.append({
                'name': product.name,
                'price': product.price,
                'image': images[0],
                'product_id': str(product.id),
            })
        context = {'product_details': product_details}
        return render(request, 'product.html', context)


class ProductDetailView(View):
    http_method_names = ['get', 'post']

    def get(self, request: any, product_id: str) -> HttpResponse:
        pid = int(product_id)
        product = Product.objects.get(pk=pid)
        images = Image.objects.filter(product__name=product.name)
        comments = Comment.objects.filter(product__name=product.name)
        comment_details = []
        for comment in comments:
            comment_details.append({
                'author': comment.author.user_profile.username,
                'content': comment.content,
                'rate': str(comment.rating)
            })

        context = {
            'name': product.name,
            'price': product.price,
            'description': product.description,
            'special_property': product.special_property,
            'category': product.category,
            'images': images,
            'comments': comments,
            }

        return render(request, 'single.html', context)

furniture_shop/products/templates/product.html
{% extends 'BaseTemplate.html' %}
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
    {% block title %}Products{% endblock %}
</head>

<body>
{% block content %}
    <div class="fh5co-loader"></div>
    <div id="page">
        <nav class="fh5co-nav" role="navigation">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-xs-2">
                        <div id="fh5co-logo"><a href="{% url 'products:product_list' %}">Shop.</a></div>
                    </div>
                    <div class="col-md-6 col-xs-6 text-center menu-1">
                        <ul>
                            <li>
                                <a href="{% url 'products:index'  %}">Home</a>
                            </li>
                            <li class="active">
                                <a class="active" href="{% url 'products:product_list' %}"><b>Shop</b></a>
                            </li>
                            <li><a href="{% url 'about:about' %}">About</a></li>
                            <li class="has-dropdown">
                                <a href="{% url 'about:services' %}">Services</a>
                                <ul class="dropdown">
                                    <li><a href="#">Web Design</a></li>
                                    <li><a href="#">eCommerce</a></li>
                                    <li><a href="#">Branding</a></li>
                                    <li><a href="#">API</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'about:contact' %}">Contact</a></li>
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'user:profile' %}">{{ user.username }}</a></li>
                            {% else %}
                                <li><a href="{% url 'user:login' %}">Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="col-md-3 col-xs-4 text-right hidden-xs menu-2">
                        <ul>
                            <li class="search">
                                <div class="input-group">
                                    <input type="text" placeholder="Search..">
                                    <span class="input-group-btn">
						        <button class="btn btn-primary" type="button"><i class="icon-search"></i></button>
						      </span>
                                </div>
                            </li>
                            <li class="shopping-cart"><a href="#" class="cart"><span><small>0</small><i class="icon-shopping-cart"></i></span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

        <header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background-image:url({% static 'images/img_bg_1.jpg' %});">
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center">
                        <div class="display-t">
                            <div class="display-tc animate-box" data-animate-effect="fadeIn">
                                <h1>Product</h1>
                                <h2>Free html5 templates by <a href="https://themewagon.com/theme_tag/free/" target="_blank">Themewagon</a></h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <div id="fh5co-product">
            <div class="container">
                <div class="row animate-box">
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <span>Cool Stuff</span>
                        <h2>Products.</h2>
                        <p>Dignissimos asperiores vitae velit veniam totam fuga molestias accusamus alias autem provident. Odit ab aliquam dolor eius.</p>
                    </div>
                </div>
                <div class="row">
                    <!-- === === === === === === === === === products === === === === === === === === === -->
                    {% for product in product_details %}
                        <div class="col-md-4 text-center animate-box">
                            <div class="product">
                                <div class="product-grid" style="background-image:url({{ product.image }});">
                                    <div class="inner">
                                        <p>
                                            <a href="" class="icon"><i class="icon-shopping-cart"></i></a>
                                            <a href="{% url 'products:product_detail' product.product_id %}" class="icon">
                                                <i class="icon-eye"></i>
                                            </a>
                                        </p>
                                    </div>
                                </div>
                                <div class="desc">
                                    <h3><a href="{% url 'products:product_detail' product.product_id %}">{{ product.name }}</a></h3>
                                    <span class="price">{{ product.price }}</span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <!-- === === === === === === === === === end products === === === === === === === === === -->
                </div>
            </div>
        </div>
    </div>

    <div id="fh5co-started">
        <div class="container">
            <div class="row animate-box">
                <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                    <h2>Newsletter</h2>
                    <p>Just stay tune for our latest Product. Now you can subscribe</p>
                </div>
            </div>
            <div class="row animate-box">
                <div class="col-md-8 col-md-offset-2">
                    <form class="form-inline">
                        <div class="col-md-6 col-sm-6">
                            <div class="form-group">
                                <label for="email" class="sr-only">Email</label>
                                <input type="email" class="form-control" id="email" placeholder="Email">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <button type="submit" class="btn btn-default btn-block">Subscribe</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer id="fh5co-footer" role="contentinfo">
        <div class="container">
            <div class="row row-pb-md">
                <div class="col-md-4 fh5co-widget">
                    <h3>Shop.</h3>
                    <p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit. Eos cumque dicta adipisci architecto culpa amet.</p>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                    <ul class="fh5co-footer-links">
                        <li><a href="#">About</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="#">Terms</a></li>
                        <li><a href="#">Meetups</a></li>
                    </ul>
                </div>

                <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                    <ul class="fh5co-footer-links">
                        <li><a href="#">Shop</a></li>
                        <li><a href="#">Privacy</a></li>
                        <li><a href="#">Testimonials</a></li>
                        <li><a href="#">Handbook</a></li>
                        <li><a href="#">Held Desk</a></li>
                    </ul>
                </div>

                <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                    <ul class="fh5co-footer-links">
                        <li><a href="#">Find Designers</a></li>
                        <li><a href="#">Find Developers</a></li>
                        <li><a href="#">Teams</a></li>
                        <li><a href="#">Advertise</a></li>
                        <li><a href="#">API</a></li>
                    </ul>
                </div>
            </div>

            <div class="row copyright">
                <div class="col-md-12 text-center">
                    <p>
                        <small class="block">&copy; 2016 Free HTML5. All Rights Reserved.</small>
                        <small class="block">Designed by <a href="http://freehtml5.co/" target="_blank">FreeHTML5.co</a> Demo Images: <a href="http://blog.gessato.com/" target="_blank">Gessato</a> &amp; <a href="http://unsplash.co/" target="_blank">Unsplash</a></small>
                    </p>
                    <p>
                    <ul class="fh5co-social-icons">
                        <li><a href="#"><i class="icon-twitter"></i></a></li>
                        <li><a href="#"><i class="icon-facebook"></i></a></li>
                        <li><a href="#"><i class="icon-linkedin"></i></a></li>
                        <li><a href="#"><i class="icon-dribbble"></i></a></li>
                    </ul>
                    </p>
                </div>
            </div>

        </div>
    </footer>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
    </div>
{% endblock %}

</body>
</html>