furniture_shop/about_us/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from .views import AboutUs, Contact, Services
from furniture_shop.settings import MEDIA_URL, MEDIA_ROOT



app_name = 'about'


urlpatterns = [
    path('', AboutUs.as_view(), name='about'),
    path('contact/', Contact.as_view(), name='contact'),
    path('services/', Services.as_view(), name='services'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

furniture_shop/furniture_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from furniture_shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('about/', include('about_us.urls', namespace='about')),
    path('user/', include('user.urls', namespace='user')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

furniture_shop/products/urls.py
from django.urls import path, include
from .views import IndexView, ProductsView, ProductDetailView
from furniture_shop.settings import MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static


app_name = 'products'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('products/', ProductsView.as_view(), name='product_list'),
    path('products/<str:product_id>/', ProductDetailView.as_view(), name='product_detail'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

furniture_shop/user/urls.py
from django.urls import path
from .views import LoginView, RegisterView, UserProfileView, logout_view, UserProfileEdit
from django.conf.urls.static import static
from furniture_shop.settings import MEDIA_ROOT, MEDIA_URL

app_name = 'user'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('logout/', logout_view, name='logout'),
    path('profile/edit/', UserProfileEdit.as_view(), name='profile_edit'),
] + static(MEDIA_URL,document_root=MEDIA_ROOT)

furniture_shop/user/models.py
# from products.models import Product
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    user_profile = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pictures', default='profile_pictures/default.png')

    def __str__(self):
        return self.user_profile.username

furniture_shop/user/views.py
from django.db import IntegrityError
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.contrib.auth import login, logout, authenticate
from products.views import IndexView
from django.contrib.auth.models import User
from .models import Customer
from products.models import Product, Basket, BoughtItem



class LoginView(View):
    http_method_names = ['get', 'post']
    template_name = 'login.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('user:profile')
        return render(request, 'login.html')

    def post(self, request):
        if request.user.is_authenticated:
            return redirect('user:profile')
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)
        if False in [username, password]:
            return render(request, 'login.html', {'error': "enter username and password"})

        user = authenticate(username=username, password=password)

        if user in User.objects.filter(username=username):
            try:
                login(request, user)
                return redirect('products:index')
            except user.DoesNotExist:
                return render(request, 'login.html', {'error': "this username does not exist!"})
        return render(request, 'login.html', {'error': "wrong username or password!"})


class RegisterView(View):
    http_method_names = ['get', 'post']
    template_name = 'register.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('user:profile')
        return render(request, 'register.html')

    def post(self, request):
        if request.user.is_authenticated:
            return redirect('user:profile')
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)
        email = request.POST.get('email', False)
        if False in [username, password, email]:
            return render(request, 'register.html', {'error': "enter username and password!"})
        user = authenticate(username=username, password=password, email=email)
        if user in User.objects.filter(username=username):
            return render(request, 'register.html', {'error': "this username already exists!"})
        try:
            user = User.objects.create_user(username=username, password=password, email=email)
            user.save()
            costumer = Customer.objects.create(user_profile=user)
            costumer.save()
            login(request, user)
            return redirect('user:profile')
        except IntegrityError:
            return render(request, 'register.html', {'error': "this email already exists!"})


class UserProfileView(View):
    http_method_names = ['get',]
    template_name = 'profile.html'

    def get(self, request):
        basket = []
        bought_items = []
        user_basket = Basket.objects.filter(user_id=request.user.id)
        user_bought_items = BoughtItem.objects.filter(user_id=request.user.id)
        profile_picture = Customer.objects.get(user_profile_id=request.user.id).profile_picture
        for basket_item in user_basket:
            basket.append({
                'product_id': basket_item.id,
                'name': basket_item.name,
                'price': basket_item.price,
            })

        for bought_item in user_bought_items:
            bought_items.append({
                'product_id': bought_item.id,
                'name': bought_item.name,
                'price': bought_item.price,
            })
        context = {
            'basket': basket,
            'bought_items': bought_items,
            'profile_picture': profile_picture.url,
        }

        return render(request, self.template_name, context)


class UserProfileEdit(View):
    http_method_names = ['get', 'post']
    template_name = 'edit_profile.html'

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('user:login')
        customer = Customer.objects.get(user_profile_id=request.user.id)
        profile_pic = customer.profile_picture.url
        return render(request, self.template_name, {'profile_pic': profile_pic})

    def post(self, request):
        if not request.user.is_authenticated:
            return redirect('user:login')
        user = request.user
        customer = Customer.objects.get(user_profile_id=request.user.id)

        new_first_name = request.POST.get('new_first_name', False)
        new_last_name = request.POST.get('new_last_name', False)
        new_email = request.POST.get('new_email', False)
        new_profile = request.FILES.get('new_profile_picture', False)

        if new_profile:
            customer.profile_picture = new_profile
            customer.save()
        if new_first_name:
            user.first_name = new_first_name
            user.save()
        if new_last_name:
            user.last_name = new_last_name
            user.save()
        if new_email:
            user.email = new_email
            user.save()
        return redirect('user:profile')

def logout_view(req):
    if not req.user.is_authenticated:
        return redirect('products:index')
    user = req.user
    logout(req)
    return redirect('products:index')

furniture_shop/user/templates/edit_profile.html
{% extends 'BaseTemplate.html' %}
{% load  static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
    {% block title %}Login{% endblock %}
</head>
<form>
    {% block content %}
        <div class="fh5co-loader"></div>

        <div id="page">
            <nav class="fh5co-nav" role="navigation">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 col-xs-2">
                            <div id="fh5co-logo"><a href="{% url 'products:index' %}">Shop.</a></div>
                        </div>
                        <div class="col-md-6 col-xs-6 text-center menu-1">
                            <ul>
                                <li>
                                    <a href="{% url 'products:index'  %}">Home</a>
                                </li>
                                <li class="has-dropdown">
                                    <a href="{% url 'products:product_list' %}">Shop</a>
                                </li>
                                <li><a href="{% url 'about:about' %}">About</a></li>
                                <li class="has-dropdown">
                                    <a href="{% url 'about:services' %}">Services</a>
                                    <ul class="dropdown">
                                        <li><a href="#">Web Design</a></li>
                                        <li><a href="#">eCommerce</a></li>
                                        <li><a href="#">Branding</a></li>
                                        <li><a href="#">API</a></li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'about:contact' %}">Contact</a></li>

                                <li class="active"><a href="{% url 'user:login' %}"><b>Login</b></a></li>

                            </ul>
                        </div>
                        <div class="col-md-3 col-xs-4 text-right hidden-xs menu-2">
                            <ul>
                                <li class="search">
                                    <div class="input-group">
                                        <input type="text" placeholder="Search..">
                                        <span class="input-group-btn">
						        <button class="btn btn-primary" type="button"><i class="icon-search"></i></button>
						      </span>
                                    </div>
                                </li>
                                <li class="shopping-cart"><a href="#" class="cart"><span><small>0</small><i class="icon-shopping-cart"></i></span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>

        </div>


        <div class="fh5co-loader"></div>

        <div id="page">
        <nav class="fh5co-nav" role="navigation">
            <div id="fh5co-started">
                <div class="container">

                    <form action="{% url 'user:profile_edit' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row animate-box">
                            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                                <h2>edit your profile</h2>
                            </div>
                        </div>
                        <div class="row animate-box">
                            <div class="col-md-8 col-md-offset-2">

                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <h2 class="btn btn-default btn-block"><label for="new_first_name">username</label></h2>
                                        <h2 class="btn btn-default btn-block">email</h2>
                                        <h2 class="btn btn-default btn-block"><label for="new_email">new email:</label></h2>
                                        <h2 class="btn btn-default btn-block">your first name:</h2>
                                        <h2 class="btn btn-default btn-block"><label for="new_first_name">edit your first name:</label></h2>
                                        <h2 class="btn btn-default btn-block">your last name:</h2>
                                        <h2 class="btn btn-default btn-block"><label for="new_last_name">edit your last name:</label></h2>
                                        <h2 class="btn btn-default btn-block">edit your profile picture</h2>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6">
                                    <h3 class="btn btn-default btn-block">{{ user.username }}</h3>
                                    <h3 class="btn btn-default btn-block" style="margin-bottom: 0">{{ user.email }}</h3>
                                    <input class="form-control btn btn-default btn-block" type="email" name="new_email" style="margin-top: 5px; margin-bottom: 0; background-color: #8c8c8c" id="new_email">
                                    {% if user.first_name %}
                                        <h3 class="btn btn-default btn-block" style="margin-bottom: 0">{{ user.first_name }}</h3>
                                    {% else %}
                                        <h3 class="btn btn-default btn-block" style="margin-bottom: 0">not set!</h3>
                                    {% endif %}
                                    <input class="form-control btn btn-default btn-block" type="text" name="new_first_name" style="margin-top: 4px; margin-bottom: 0; background-color: #8c8c8c" id="new_first_name">
                                    {% if user.last_name %}
                                        <h3 class="btn btn-default btn-block" style="margin-bottom: 0">{{ user.last_name }}</h3>
                                    {% else %}
                                        <h3 class="btn btn-default btn-block" style="margin-bottom: 0">not set!</h3>
                                    {% endif %}
                                    <input class="form-control btn btn-default btn-block" type="text" name="new_last_name" style="margin-top: 4px; margin-bottom: 0; background-color: #8c8c8c" id="new_last_name">
                                    <label for="imgc"><img src="{{ profile_pic }}" alt=""></label>
                                    <input type="file" name="new_profile_picture" id="imgc" >

                                </div>
                            </div>
                        </div>
                        <div class="row animate-box">
                            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                                <input class="col-md-8 col-md-offset-2 text-center fh5co-heading" type="submit" name="edit" id="btn" value="edit">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </nav>


        <div class="gototop js-top">
            <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
        </div>

    {% endblock %}

    </body>
</html>

furniture_shop/user/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

furniture_shop/user/templates/profile.html
{% extends 'BaseTemplate.html' %}
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    {% block title %}AboutUs{% endblock %}
</head>
<body>
{% block content %}

    <div class="fh5co-loader"></div>

    <div id="page">
        <nav class="fh5co-nav" role="navigation">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-xs-2">
                        <div id="fh5co-logo"><a href="{% url 'products:index' %}">Shop.</a></div>
                    </div>
                    <!-- ===================== header options ===================== -->
                    <div class="col-md-6 col-xs-6 text-center menu-1">
                        <ul>
                            <li>
                                <a href="{% url 'products:index'  %}">Home</a>
                            </li>
                            <li class="has-dropdown">
                                <a href="{% url 'products:product_list' %}">Shop</a>
                            </li>
                            <li><a href="{% url 'about:about' %}">About</a></li>
                            <li class="has-dropdown">
                                <a href="{% url 'about:services' %}">Services</a>
                                <ul class="dropdown">
                                    <li><a href="#">Web Design</a></li>
                                    <li><a href="#">eCommerce</a></li>
                                    <li><a href="#">Branding</a></li>
                                    <li><a href="#">API</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'about:contact' %}">Contact</a></li>

                            {% if user.is_authenticated %}
                                <li class="active"><a href="{% url 'user:profile' %}"><b>{{ user.username }}</b></a></li>
                            {% else %}
                                <li class="active"><a href="{% url 'user:login' %}"><b>Login</b></a></li>
                            {% endif %}

                        </ul>
                    </div>
                    <!-- ===================== header options ===================== -->
                    <div class="col-md-3 col-xs-4 text-right hidden-xs menu-2">
                        <ul>
                            <li class="search">
                                <div class="input-group">
                                    <input type="text" placeholder="Search..">
                                    <span class="input-group-btn">
						        <button class="btn btn-primary" type="button"><i class="icon-search"></i></button>
						      </span>
                                </div>
                            </li>
                            <li class="shopping-cart"><a href="#" class="cart"><span><small>0</small><i class="icon-shopping-cart"></i></span></a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </nav>
        <div id="fh5co-about">
            <div class="container">
                <div class="about-content">
                    <div class="row animate-box">
                        <div class="col-md-6">
                            <div class="desc">
                                <h3>username : {{ user.username }}</h3>
                                <a href="{% url 'user:logout' %}"><button type="submit" >logout</button></a>
                                <a href="{% url 'user:profile_edit' %}"><button type="submit" >edit your profile</button></a>
                                <h3>first name : {{ user.first_name }}</h3>
                                <h3>last name : {{ user.last_name }}</h3>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <img class="img-responsive" src="{{ profile_picture }}" alt="about">
                        </div>
                    </div>
                </div>

                <div class="row animate-box">
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <span>your activities</span>
                        <h2>your previously bought:</h2>
                    </div>
                </div>
                <div class="row">
                    {% for product in basket %}
                        <div class="col-md-4 col-sm-4 animate-box" data-animate-effect="fadeIn">
                        <div class="fh5co-staff">
                        <img src="{{ product.image }}" alt="product image">
                        <h3>{{ product.name }}</h3>
                        <strong class="role">{{ product.price }}</strong>
                    {% empty %}
                        <div class="row animate-box">
                            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                                <h2>no item in basket!</h2>
                            </div>
                        </div>
                    {% endfor %}

                    {% for product in bought_items %}
                        <div class="col-md-4 col-sm-4 animate-box" data-animate-effect="fadeIn">
                        <div class="fh5co-staff">
                        <img src="{{ product.image }}" alt="product image">
                        <h3>{{ product.name }}</h3>
                        <strong class="role">{{ product.price }}</strong>
                    {% empty %}
                        <div class="row animate-box">
                            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                                <h2>no previously bought items!</h2>
                            </div>
                        </div>
                    {% endfor %}

                    </div>
                    </div>
                    </div>
                    </div>
                </div>

                <div id="fh5co-started">
                    <div class="container">
                        <div class="row animate-box">
                            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                                <h2>Newsletter</h2>
                                <p>Just stay tune for our latest Product. Now you can subscribe</p>
                            </div>
                        </div>
                        <div class="row animate-box">
                            <div class="col-md-8 col-md-offset-2">
                                <form class="form-inline">
                                    <div class="col-md-6 col-sm-6">
                                        <div class="form-group">
                                            <label for="email" class="sr-only">Email</label>
                                            <input type="email" class="form-control" id="email" placeholder="Email">
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6">
                                        <button type="submit" class="btn btn-default btn-block">Subscribe</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <footer id="fh5co-footer" role="contentinfo">
                    <div class="container">
                        <div class="row row-pb-md">
                            <div class="col-md-4 fh5co-widget">
                                <h3>Shop.</h3>
                                <p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit. Eos cumque dicta adipisci architecto culpa amet.</p>
                            </div>
                            <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                                <ul class="fh5co-footer-links">
                                    <li><a href="{% url 'about:about' %}">About</a></li>
                                    <li><a href="#">Help</a></li>
                                    <li><a href="{% url 'about:contact' %}">Contact</a></li>
                                    <li><a href="#">Terms</a></li>
                                    <li><a href="#">Meetups</a></li>
                                </ul>
                            </div>

                            <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                                <ul class="fh5co-footer-links">
                                    <li><a href="#">Shop</a></li>
                                    <li><a href="#">Privacy</a></li>
                                    <li><a href="#">Testimonials</a></li>
                                    <li><a href="#">Handbook</a></li>
                                    <li><a href="#">Held Desk</a></li>
                                </ul>
                            </div>

                            <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                                <ul class="fh5co-footer-links">
                                    <li><a href="#">Find Designers</a></li>
                                    <li><a href="#">Find Developers</a></li>
                                    <li><a href="#">Teams</a></li>
                                    <li><a href="#">Advertise</a></li>
                                    <li><a href="#">API</a></li>
                                </ul>
                            </div>
                        </div>

                        <div class="row copyright">
                            <div class="col-md-12 text-center">
                                <p>
                                    <small class="block">&copy; 2016 Free HTML5. All Rights Reserved.</small>
                                    <small class="block">Designed by <a href="http://freehtml5.co/" target="_blank">FreeHTML5.co</a> Demo Images: <a href="http://blog.gessato.com/" target="_blank">Gessato</a> &amp; <a href="http://unsplash.co/" target="_blank">Unsplash</a></small>
                                </p>
                                <p>
                                <ul class="fh5co-social-icons">
                                    <li><a href="#"><i class="icon-twitter"></i></a></li>
                                    <li><a href="#"><i class="icon-facebook"></i></a></li>
                                    <li><a href="#"><i class="icon-linkedin"></i></a></li>
                                    <li><a href="#"><i class="icon-dribbble"></i></a></li>
                                </ul>
                                </p>
                            </div>
                        </div>

                    </div>
                </footer>
            </div>
        </div>
    </div>
    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
    </div>

{% endblock %}
</body>
</html>